# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'som.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 600)
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 931, 621))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(39, 39, 39)\n"
"    }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 101, 41))
        self.label_2.setStyleSheet("\n"
"font: 24pt \"Tw Cen MT Condensed\";\n"
"color: rgb(227, 227, 227);")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 330, 231, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 151, 71))
        self.label_5.setStyleSheet("\n"
"font: 27pt \"Tw Cen MT Condensed\";\n"
"color: rgb(227, 227, 227);")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 90, 591, 41))
        self.lineEdit.setStyleSheet("\n"
"QLineEdit {\n"
"     border-width: 1px;\n"
"\n"
"     border-style: solid;\n"
"     border-color: white;\n"
"    color: rgb(227, 227, 227);\n"
"    \n"
"    font: 10pt \"Lucida Fax\";\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"background-color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"\n"
"border-style: solid;\n"
"border-color: black;\n"
"}\n"
"\n"
"QLineEdit::clicked {\n"
"background color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"\n"
"border-style: solid;\n"
"border-color: black;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 161, 51))
        self.label_3.setStyleSheet("\n"
"font: 24pt \"Tw Cen MT Condensed\";\n"
"color: rgb(227, 227, 227);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 190, 431, 41))
        self.lineEdit_2.setStyleSheet("\n"
"QLineEdit {\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: white;\n"
"    color: rgb(227, 227, 227);\n"
"    \n"
"    font: 10pt \"Lucida Fax\";\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"background-color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"}\n"
"\n"
"QLineEdit::clicked {\n"
"background color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 171, 61))
        self.label_4.setStyleSheet("\n"
"font: 27pt \"Tw Cen MT Condensed\";\n"
"color: rgb(227, 227, 227);")
        self.label_4.setObjectName("label_4")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 290, 111, 61))
        self.radioButton_2.setStyleSheet("\n"
"color: rgb(227, 227, 227);\n"
"font: 17pt \"Lucida Fax\";\n"
"")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 510, 201, 61))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 39, 39);\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: white;\n"
"    \n"
"    font: 12pt \"Lucida Fax\";\n"
"    color:rgb(227, 227, 227);\n"
" }\n"
"QPushButton::hover {\n"
"background-color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"}\n"
"\n"
"QPushButton::clicked {\n"
"background color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 190, 161, 41))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 39, 39);\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: white;\n"
"    \n"
"    font: 8pt \"Lucida Fax\";\n"
"    color:rgb(227, 227, 227);\n"
" }\n"
"QPushButton::hover {\n"
"background-color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"}\n"
"\n"
"QPushButton::clicked {\n"
"background color: rgb(32, 32, 32);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(200, 290, 111, 61))
        self.radioButton.setStyleSheet("\n"
"    color: rgb(227, 227, 227);\n"
"    \n"
"    font: 17pt \"Lucida Fax\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 410, 161, 41))
        self.radioButton_3.setStyleSheet("\n"
"color: rgb(227, 227, 227);\n"
"font: 17pt \"Lucida Fax\";\n"
"")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 450, 181, 41))
        self.radioButton_4.setStyleSheet("\n"
"color: rgb(227, 227, 227);\n"
"font: 17pt \"Lucida Fax\";\n"
"")
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_7.setGeometry(QtCore.QRect(330, 410, 121, 41))
        self.radioButton_7.setStyleSheet("\n"
"color: rgb(227, 227, 227);\n"
"font: 17pt \"Lucida Fax\";\n"
"")
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_6.setGeometry(QtCore.QRect(470, 410, 141, 41))
        self.radioButton_6.setStyleSheet("\n"
"color: rgb(227, 227, 227);\n"
"font: 17pt \"Lucida Fax\";\n"
"")
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_5.setGeometry(QtCore.QRect(200, 410, 121, 41))
        self.radioButton_5.setStyleSheet("\n"
"color: rgb(227, 227, 227);\n"
"font: 17pt \"Lucida Fax\";\n"
"")
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.label_2.raise_()
        self.frame_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_8.raise_()
        self.lineEdit_2.raise_()
        self.radioButton_2.raise_()
        self.lineEdit.raise_()
        self.radioButton.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_7.raise_()
        self.radioButton_6.raise_()
        self.radioButton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download"))
        self.label_2.setText(_translate("MainWindow", "link:"))
        self.label_5.setText(_translate("MainWindow", "quality"))
        self.label_3.setText(_translate("MainWindow", "exit path:"))
        self.label_4.setText(_translate("MainWindow", "format:"))
        self.radioButton_2.setText(_translate("MainWindow", "mp3"))
        self.pushButton_2.setText(_translate("MainWindow", "Download"))
        self.pushButton_8.setText(_translate("MainWindow", "select"))
        self.radioButton.setText(_translate("MainWindow", "mp4"))
        self.radioButton_3.setText(_translate("MainWindow", "Highest"))
        self.radioButton_4.setText(_translate("MainWindow", "Lowest"))
        self.radioButton_7.setText(_translate("MainWindow", "720p"))
        self.radioButton_6.setText(_translate("MainWindow", "1080p"))
        self.radioButton_5.setText(_translate("MainWindow", "480p"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

